# Generated by Django 4.0.2 on 2022-03-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='items',
            name='created',
            field=models.DateField(default='2022-03-01'),
        ),
        migrations.AddField(
            model_name='items',
            name='due_date',
            field=models.DateField(default='2022-03-01'),
        ),
        migrations.AlterField(
            model_name='items',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
