# Generated by Django 4.0.2 on 2022-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_items_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(default='Create Task', max_length=250),
        ),
    ]
