# Generated by Django 4.0.2 on 2022-03-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_items_due_date_alter_items_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='due_date',
            field=models.DateField(default='2022-03-02'),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateField(default='2022-03-02'),
        ),
    ]
